import SwiftUI

enum ThemeLibrary {
    static var allThemes: [HUDTheme] {
        appleThemes + cyberpunkThemes + japaneseThemes +
        europeanThemes + kawaiiThemes + militaryThemes +
        retroFutureThemes + zenThemes + neonCityThemes + nordicThemes
    }

    // MARK: - 1. Apple Standard（免费）

    static let appleStandard = HUDTheme(
        id: "apple_standard",
        styleFamily: .apple,
        name: "Apple Standard",
        subtitle: "Clean & Elegant",
        previewImageName: "theme_apple_standard",
        isPremium: false,
        trialDurationMinutes: 0,
        primaryHex: "007AFF",
        secondaryHex: "5856D6",
        accentHex: "34C759",
        backgroundHex: "1C1C1E",
        alertInfoHex: "007AFF",
        alertCautionHex: "FF9500",
        alertWarningHex: "FF3B30",
        alertCriticalHex: "FF2D55",
        textPrimaryHex: "FFFFFF",
        textSecondaryHex: "8E8E93",
        cornerRadius: 16,
        borderWidth: 1,
        glassOpacity: 0.15,
        blurRadius: 20,
        fontDesign: .standard,
        iconStyle: .sfSymbol,
        animationStyle: .smooth,
        radarStyle: .classic,
        radarRingCount: 3,
        radarSweepEnabled: true
    )

    static let appleThemes: [HUDTheme] = [
        appleStandard,
        HUDTheme(
            id: "apple_dark",
            styleFamily: .apple,
            name: "Apple Dark Pro",
            subtitle: "Pure Darkness",
            previewImageName: "theme_apple_dark",
            isPremium: false,
            trialDurationMinutes: 0,
            primaryHex: "0A84FF",
            secondaryHex: "5E5CE6",
            accentHex: "30D158",
            backgroundHex: "000000",
            alertInfoHex: "0A84FF",
            alertCautionHex: "FFD60A",
            alertWarningHex: "FF453A",
            alertCriticalHex: "FF375F",
            textPrimaryHex: "FFFFFF",
            textSecondaryHex: "98989D",
            cornerRadius: 14,
            borderWidth: 0.5,
            glassOpacity: 0.1,
            blurRadius: 25,
            fontDesign: .standard,
            iconStyle: .sfSymbol,
            animationStyle: .smooth,
            radarStyle: .classic,
            radarRingCount: 3,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "apple_light",
            styleFamily: .apple,
            name: "Apple Light",
            subtitle: "Bright & Clear",
            previewImageName: "theme_apple_light",
            isPremium: false,
            trialDurationMinutes: 0,
            primaryHex: "007AFF",
            secondaryHex: "5856D6",
            accentHex: "34C759",
            backgroundHex: "F2F2F7",
            alertInfoHex: "007AFF",
            alertCautionHex: "FF9500",
            alertWarningHex: "FF3B30",
            alertCriticalHex: "FF2D55",
            textPrimaryHex: "1C1C1E",
            textSecondaryHex: "8E8E93",
            cornerRadius: 16,
            borderWidth: 1,
            glassOpacity: 0.3,
            blurRadius: 15,
            fontDesign: .rounded,
            iconStyle: .sfSymbol,
            animationStyle: .smooth,
            radarStyle: .classic,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
    ]

    // MARK: - 2. Cyberpunk 赛博朋克

    static let cyberpunkThemes: [HUDTheme] = [
        HUDTheme(
            id: "cyber_neon",
            styleFamily: .cyberpunk,
            name: "Neon Overload",
            subtitle: "电光幻影",
            previewImageName: "theme_cyber_neon",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "00D4FF",
            secondaryHex: "FF00FF",
            accentHex: "39FF14",
            backgroundHex: "0A0A1A",
            alertInfoHex: "00D4FF",
            alertCautionHex: "FFB800",
            alertWarningHex: "FF4500",
            alertCriticalHex: "FF0040",
            textPrimaryHex: "E0E0FF",
            textSecondaryHex: "6B6B8D",
            cornerRadius: 4,
            borderWidth: 2,
            glassOpacity: 0.08,
            blurRadius: 10,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .glitch,
            radarStyle: .tactical,
            radarRingCount: 5,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "cyber_red",
            styleFamily: .cyberpunk,
            name: "Red District",
            subtitle: "深紅地帯",
            previewImageName: "theme_cyber_red",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FF1744",
            secondaryHex: "D50000",
            accentHex: "FF5252",
            backgroundHex: "120000",
            alertInfoHex: "FF5252",
            alertCautionHex: "FFAB00",
            alertWarningHex: "FF6D00",
            alertCriticalHex: "FF1744",
            textPrimaryHex: "FFCDD2",
            textSecondaryHex: "8B4049",
            cornerRadius: 2,
            borderWidth: 1.5,
            glassOpacity: 0.06,
            blurRadius: 8,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .glitch,
            radarStyle: .tactical,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "cyber_ghost",
            styleFamily: .cyberpunk,
            name: "Ghost Protocol",
            subtitle: "幽灵协议",
            previewImageName: "theme_cyber_ghost",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "00E5FF",
            secondaryHex: "1DE9B6",
            accentHex: "76FF03",
            backgroundHex: "0D1117",
            alertInfoHex: "00E5FF",
            alertCautionHex: "FFD740",
            alertWarningHex: "FF6E40",
            alertCriticalHex: "FF1744",
            textPrimaryHex: "B0BEC5",
            textSecondaryHex: "546E7A",
            cornerRadius: 6,
            borderWidth: 1,
            glassOpacity: 0.05,
            blurRadius: 12,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .glitch,
            radarStyle: .tactical,
            radarRingCount: 5,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "cyber_gold",
            styleFamily: .cyberpunk,
            name: "Corpo Elite",
            subtitle: "企業精英",
            previewImageName: "theme_cyber_gold",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FFD700",
            secondaryHex: "FFA000",
            accentHex: "FFAB00",
            backgroundHex: "1A1400",
            alertInfoHex: "FFD700",
            alertCautionHex: "FF6F00",
            alertWarningHex: "FF3D00",
            alertCriticalHex: "DD2C00",
            textPrimaryHex: "FFF8E1",
            textSecondaryHex: "8D6E00",
            cornerRadius: 0,
            borderWidth: 2,
            glassOpacity: 0.07,
            blurRadius: 8,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .snappy,
            radarStyle: .tactical,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
    ]

    // MARK: - 3. Japanese 和風

    static let japaneseThemes: [HUDTheme] = [
        HUDTheme(
            id: "jp_sakura",
            styleFamily: .japanese,
            name: "桜 Sakura",
            subtitle: "桜の季節",
            previewImageName: "theme_jp_sakura",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FFB7C5",
            secondaryHex: "FF69B4",
            accentHex: "C71585",
            backgroundHex: "1A0A10",
            alertInfoHex: "FFB7C5",
            alertCautionHex: "FFD700",
            alertWarningHex: "FF8C00",
            alertCriticalHex: "DC143C",
            textPrimaryHex: "FFF0F5",
            textSecondaryHex: "9B6A7A",
            cornerRadius: 20,
            borderWidth: 1,
            glassOpacity: 0.12,
            blurRadius: 18,
            fontDesign: .serif,
            iconStyle: .filled,
            animationStyle: .organic,
            radarStyle: .decorative,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "jp_sumi",
            styleFamily: .japanese,
            name: "墨 Sumi-e",
            subtitle: "水墨画の世界",
            previewImageName: "theme_jp_sumi",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "D7CCC8",
            secondaryHex: "8D6E63",
            accentHex: "A1887F",
            backgroundHex: "1A1610",
            alertInfoHex: "BCAAA4",
            alertCautionHex: "FFB74D",
            alertWarningHex: "FF7043",
            alertCriticalHex: "E53935",
            textPrimaryHex: "EFEBE9",
            textSecondaryHex: "795548",
            cornerRadius: 8,
            borderWidth: 1.5,
            glassOpacity: 0.1,
            blurRadius: 15,
            fontDesign: .serif,
            iconStyle: .filled,
            animationStyle: .organic,
            radarStyle: .decorative,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "jp_wave",
            styleFamily: .japanese,
            name: "波 Nami",
            subtitle: "神奈川沖の浪裏",
            previewImageName: "theme_jp_wave",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "1565C0",
            secondaryHex: "0D47A1",
            accentHex: "E8EAF6",
            backgroundHex: "0A1628",
            alertInfoHex: "42A5F5",
            alertCautionHex: "FFD54F",
            alertWarningHex: "FF7043",
            alertCriticalHex: "E53935",
            textPrimaryHex: "E3F2FD",
            textSecondaryHex: "5C6BC0",
            cornerRadius: 12,
            borderWidth: 2,
            glassOpacity: 0.12,
            blurRadius: 20,
            fontDesign: .serif,
            iconStyle: .filled,
            animationStyle: .organic,
            radarStyle: .decorative,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
    ]

    // MARK: - 4. European Classical 欧式古典

    static let europeanThemes: [HUDTheme] = [
        HUDTheme(
            id: "eu_royal",
            styleFamily: .europeanClassical,
            name: "Royal Gold",
            subtitle: "Palace Grandeur",
            previewImageName: "theme_eu_royal",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "DAA520",
            secondaryHex: "B8860B",
            accentHex: "FFD700",
            backgroundHex: "1A0F00",
            alertInfoHex: "DAA520",
            alertCautionHex: "CD853F",
            alertWarningHex: "D2691E",
            alertCriticalHex: "8B0000",
            textPrimaryHex: "FAEBD7",
            textSecondaryHex: "8B7355",
            cornerRadius: 12,
            borderWidth: 2.5,
            glassOpacity: 0.15,
            blurRadius: 12,
            fontDesign: .serif,
            iconStyle: .filled,
            animationStyle: .smooth,
            radarStyle: .decorative,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "eu_marble",
            styleFamily: .europeanClassical,
            name: "Marble Hall",
            subtitle: "Renaissance Beauty",
            previewImageName: "theme_eu_marble",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "E0E0E0",
            secondaryHex: "9E9E9E",
            accentHex: "BDBDBD",
            backgroundHex: "1A1A1A",
            alertInfoHex: "90A4AE",
            alertCautionHex: "FFB74D",
            alertWarningHex: "FF8A65",
            alertCriticalHex: "C62828",
            textPrimaryHex: "F5F5F5",
            textSecondaryHex: "757575",
            cornerRadius: 10,
            borderWidth: 2,
            glassOpacity: 0.18,
            blurRadius: 15,
            fontDesign: .serif,
            iconStyle: .filled,
            animationStyle: .smooth,
            radarStyle: .decorative,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "eu_burgundy",
            styleFamily: .europeanClassical,
            name: "Burgundy Velvet",
            subtitle: "Victorian Elegance",
            previewImageName: "theme_eu_burgundy",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "800020",
            secondaryHex: "4A0012",
            accentHex: "DAA520",
            backgroundHex: "150008",
            alertInfoHex: "CE93D8",
            alertCautionHex: "FFD54F",
            alertWarningHex: "FF8A65",
            alertCriticalHex: "D50000",
            textPrimaryHex: "F3E5F5",
            textSecondaryHex: "8E4A5C",
            cornerRadius: 14,
            borderWidth: 2.5,
            glassOpacity: 0.14,
            blurRadius: 12,
            fontDesign: .serif,
            iconStyle: .filled,
            animationStyle: .smooth,
            radarStyle: .decorative,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
    ]

    // MARK: - 5. Kawaii 萌宠

    static let kawaiiThemes: [HUDTheme] = [
        HUDTheme(
            id: "kawaii_cat",
            styleFamily: .kawaii,
            name: "Neko Paradise",
            subtitle: "にゃんにゃん♪",
            previewImageName: "theme_kawaii_cat",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FF9ED2",
            secondaryHex: "FFB6D9",
            accentHex: "FF6EB4",
            backgroundHex: "1A0A14",
            alertInfoHex: "FFB6D9",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF5350",
            textPrimaryHex: "FFF0F5",
            textSecondaryHex: "C48B9F",
            cornerRadius: 24,
            borderWidth: 2,
            glassOpacity: 0.15,
            blurRadius: 20,
            fontDesign: .rounded,
            iconStyle: .filled,
            animationStyle: .bounce,
            radarStyle: .kawaii,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "kawaii_bunny",
            styleFamily: .kawaii,
            name: "Bunny Garden",
            subtitle: "うさぎの庭",
            previewImageName: "theme_kawaii_bunny",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "B39DDB",
            secondaryHex: "CE93D8",
            accentHex: "E1BEE7",
            backgroundHex: "120A1A",
            alertInfoHex: "CE93D8",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF5350",
            textPrimaryHex: "F3E5F5",
            textSecondaryHex: "9575CD",
            cornerRadius: 28,
            borderWidth: 2,
            glassOpacity: 0.14,
            blurRadius: 22,
            fontDesign: .rounded,
            iconStyle: .filled,
            animationStyle: .bounce,
            radarStyle: .kawaii,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "kawaii_panda",
            styleFamily: .kawaii,
            name: "Panda Dreamland",
            subtitle: "パンダの夢",
            previewImageName: "theme_kawaii_panda",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "80CBC4",
            secondaryHex: "4DB6AC",
            accentHex: "A5D6A7",
            backgroundHex: "0A1A18",
            alertInfoHex: "80CBC4",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF5350",
            textPrimaryHex: "E0F2F1",
            textSecondaryHex: "4DB6AC",
            cornerRadius: 22,
            borderWidth: 2.5,
            glassOpacity: 0.13,
            blurRadius: 18,
            fontDesign: .rounded,
            iconStyle: .filled,
            animationStyle: .bounce,
            radarStyle: .kawaii,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "kawaii_star",
            styleFamily: .kawaii,
            name: "Star Candy",
            subtitle: "キラキラ★",
            previewImageName: "theme_kawaii_star",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FFD54F",
            secondaryHex: "FFEE58",
            accentHex: "FFF176",
            backgroundHex: "1A1400",
            alertInfoHex: "FFD54F",
            alertCautionHex: "FFB74D",
            alertWarningHex: "FF8A65",
            alertCriticalHex: "EF5350",
            textPrimaryHex: "FFFDE7",
            textSecondaryHex: "F9A825",
            cornerRadius: 26,
            borderWidth: 2,
            glassOpacity: 0.16,
            blurRadius: 20,
            fontDesign: .rounded,
            iconStyle: .filled,
            animationStyle: .bounce,
            radarStyle: .kawaii,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
    ]

    // MARK: - 6. Military 军事战术

    static let militaryThemes: [HUDTheme] = [
        HUDTheme(
            id: "mil_tactical",
            styleFamily: .military,
            name: "Tactical Ops",
            subtitle: "Mission Ready",
            previewImageName: "theme_mil_tactical",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "76FF03",
            secondaryHex: "64DD17",
            accentHex: "00E676",
            backgroundHex: "0A1A00",
            alertInfoHex: "76FF03",
            alertCautionHex: "FFEA00",
            alertWarningHex: "FF6D00",
            alertCriticalHex: "FF1744",
            textPrimaryHex: "C5E1A5",
            textSecondaryHex: "558B2F",
            cornerRadius: 2,
            borderWidth: 1,
            glassOpacity: 0.05,
            blurRadius: 5,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .snappy,
            radarStyle: .tactical,
            radarRingCount: 5,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "mil_stealth",
            styleFamily: .military,
            name: "Stealth Mode",
            subtitle: "Dark Operations",
            previewImageName: "theme_mil_stealth",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "455A64",
            secondaryHex: "37474F",
            accentHex: "78909C",
            backgroundHex: "0A0E11",
            alertInfoHex: "607D8B",
            alertCautionHex: "FFA726",
            alertWarningHex: "FF7043",
            alertCriticalHex: "F44336",
            textPrimaryHex: "B0BEC5",
            textSecondaryHex: "455A64",
            cornerRadius: 0,
            borderWidth: 1,
            glassOpacity: 0.03,
            blurRadius: 3,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .snappy,
            radarStyle: .tactical,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "mil_desert",
            styleFamily: .military,
            name: "Desert Storm",
            subtitle: "Sand & Steel",
            previewImageName: "theme_mil_desert",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "D7CCC8",
            secondaryHex: "BCAAA4",
            accentHex: "A1887F",
            backgroundHex: "1A1510",
            alertInfoHex: "BCAAA4",
            alertCautionHex: "FFB74D",
            alertWarningHex: "FF8A65",
            alertCriticalHex: "E53935",
            textPrimaryHex: "EFEBE9",
            textSecondaryHex: "8D6E63",
            cornerRadius: 4,
            borderWidth: 1.5,
            glassOpacity: 0.06,
            blurRadius: 6,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .snappy,
            radarStyle: .tactical,
            radarRingCount: 5,
            radarSweepEnabled: true
        ),
    ]

    // MARK: - 7. Retro Future 复古未来

    static let retroFutureThemes: [HUDTheme] = [
        HUDTheme(
            id: "retro_synthwave",
            styleFamily: .retroFuture,
            name: "Synthwave",
            subtitle: "1984 Digital Dream",
            previewImageName: "theme_retro_synth",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FF6EC7",
            secondaryHex: "7B2FBE",
            accentHex: "00FFFF",
            backgroundHex: "1A0028",
            alertInfoHex: "00FFFF",
            alertCautionHex: "FFD700",
            alertWarningHex: "FF6347",
            alertCriticalHex: "FF1493",
            textPrimaryHex: "FFE4F2",
            textSecondaryHex: "9B59B6",
            cornerRadius: 8,
            borderWidth: 2,
            glassOpacity: 0.1,
            blurRadius: 15,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .smooth,
            radarStyle: .classic,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "retro_vhs",
            styleFamily: .retroFuture,
            name: "VHS Glitch",
            subtitle: "Tape Error",
            previewImageName: "theme_retro_vhs",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "00FF00",
            secondaryHex: "FF0000",
            accentHex: "0000FF",
            backgroundHex: "0A0A0A",
            alertInfoHex: "00FF00",
            alertCautionHex: "FFFF00",
            alertWarningHex: "FF8000",
            alertCriticalHex: "FF0000",
            textPrimaryHex: "E0E0E0",
            textSecondaryHex: "555555",
            cornerRadius: 0,
            borderWidth: 3,
            glassOpacity: 0.04,
            blurRadius: 8,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .glitch,
            radarStyle: .classic,
            radarRingCount: 3,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "retro_amber",
            styleFamily: .retroFuture,
            name: "Amber Terminal",
            subtitle: "Mainframe Access",
            previewImageName: "theme_retro_amber",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FFB000",
            secondaryHex: "FF8F00",
            accentHex: "FFD54F",
            backgroundHex: "0A0800",
            alertInfoHex: "FFB000",
            alertCautionHex: "FFA000",
            alertWarningHex: "FF6F00",
            alertCriticalHex: "E65100",
            textPrimaryHex: "FFE0B2",
            textSecondaryHex: "8B6914",
            cornerRadius: 0,
            borderWidth: 1,
            glassOpacity: 0.04,
            blurRadius: 5,
            fontDesign: .monospaced,
            iconStyle: .outlined,
            animationStyle: .snappy,
            radarStyle: .classic,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
    ]

    // MARK: - 8. Minimalist Zen 极简禅意

    static let zenThemes: [HUDTheme] = [
        HUDTheme(
            id: "zen_void",
            styleFamily: .minimalistZen,
            name: "Void",
            subtitle: "虚无",
            previewImageName: "theme_zen_void",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FAFAFA",
            secondaryHex: "E0E0E0",
            accentHex: "BDBDBD",
            backgroundHex: "121212",
            alertInfoHex: "90A4AE",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF9A9A",
            textPrimaryHex: "FAFAFA",
            textSecondaryHex: "616161",
            cornerRadius: 0,
            borderWidth: 0.5,
            glassOpacity: 0.05,
            blurRadius: 30,
            fontDesign: .standard,
            iconStyle: .outlined,
            animationStyle: .organic,
            radarStyle: .minimal,
            radarRingCount: 2,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "zen_breath",
            styleFamily: .minimalistZen,
            name: "Breath",
            subtitle: "呼吸",
            previewImageName: "theme_zen_breath",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "B2DFDB",
            secondaryHex: "80CBC4",
            accentHex: "4DB6AC",
            backgroundHex: "0A1614",
            alertInfoHex: "80CBC4",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF9A9A",
            textPrimaryHex: "E0F2F1",
            textSecondaryHex: "4DB6AC",
            cornerRadius: 30,
            borderWidth: 0.5,
            glassOpacity: 0.08,
            blurRadius: 25,
            fontDesign: .standard,
            iconStyle: .outlined,
            animationStyle: .organic,
            radarStyle: .minimal,
            radarRingCount: 2,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "zen_stone",
            styleFamily: .minimalistZen,
            name: "Stone Garden",
            subtitle: "枯山水",
            previewImageName: "theme_zen_stone",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "9E9E9E",
            secondaryHex: "757575",
            accentHex: "BDBDBD",
            backgroundHex: "1A1A1A",
            alertInfoHex: "9E9E9E",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF9A9A",
            textPrimaryHex: "E0E0E0",
            textSecondaryHex: "616161",
            cornerRadius: 6,
            borderWidth: 1,
            glassOpacity: 0.06,
            blurRadius: 20,
            fontDesign: .serif,
            iconStyle: .outlined,
            animationStyle: .organic,
            radarStyle: .minimal,
            radarRingCount: 2,
            radarSweepEnabled: false
        ),
    ]

    // MARK: - 9. Neon City 霓虹都市

    static let neonCityThemes: [HUDTheme] = [
        HUDTheme(
            id: "neon_tokyo",
            styleFamily: .neonCity,
            name: "Tokyo Night",
            subtitle: "東京夜景",
            previewImageName: "theme_neon_tokyo",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "E040FB",
            secondaryHex: "7C4DFF",
            accentHex: "00E5FF",
            backgroundHex: "0A0014",
            alertInfoHex: "40C4FF",
            alertCautionHex: "FFD740",
            alertWarningHex: "FF6E40",
            alertCriticalHex: "FF1744",
            textPrimaryHex: "EDE7F6",
            textSecondaryHex: "7E57C2",
            cornerRadius: 10,
            borderWidth: 1.5,
            glassOpacity: 0.08,
            blurRadius: 12,
            fontDesign: .standard,
            iconStyle: .filled,
            animationStyle: .snappy,
            radarStyle: .classic,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "neon_seoul",
            styleFamily: .neonCity,
            name: "Seoul Vibes",
            subtitle: "서울의 밤",
            previewImageName: "theme_neon_seoul",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "00BCD4",
            secondaryHex: "26C6DA",
            accentHex: "FF4081",
            backgroundHex: "001A1F",
            alertInfoHex: "26C6DA",
            alertCautionHex: "FFD740",
            alertWarningHex: "FF6E40",
            alertCriticalHex: "FF1744",
            textPrimaryHex: "E0F7FA",
            textSecondaryHex: "00ACC1",
            cornerRadius: 12,
            borderWidth: 1.5,
            glassOpacity: 0.1,
            blurRadius: 14,
            fontDesign: .rounded,
            iconStyle: .filled,
            animationStyle: .snappy,
            radarStyle: .classic,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "neon_nyc",
            styleFamily: .neonCity,
            name: "NYC Electric",
            subtitle: "Broadway Lights",
            previewImageName: "theme_neon_nyc",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FFD600",
            secondaryHex: "FF6D00",
            accentHex: "00E676",
            backgroundHex: "0A0800",
            alertInfoHex: "FFD600",
            alertCautionHex: "FF9100",
            alertWarningHex: "FF3D00",
            alertCriticalHex: "DD2C00",
            textPrimaryHex: "FFF9C4",
            textSecondaryHex: "F9A825",
            cornerRadius: 8,
            borderWidth: 2,
            glassOpacity: 0.09,
            blurRadius: 10,
            fontDesign: .standard,
            iconStyle: .filled,
            animationStyle: .snappy,
            radarStyle: .classic,
            radarRingCount: 4,
            radarSweepEnabled: true
        ),
    ]

    // MARK: - 10. Nordic 北欧极光

    static let nordicThemes: [HUDTheme] = [
        HUDTheme(
            id: "nordic_aurora",
            styleFamily: .nordic,
            name: "Aurora Borealis",
            subtitle: "Northern Lights",
            previewImageName: "theme_nordic_aurora",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "69F0AE",
            secondaryHex: "00E5FF",
            accentHex: "B388FF",
            backgroundHex: "0A1420",
            alertInfoHex: "69F0AE",
            alertCautionHex: "FFE57F",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "FF8A80",
            textPrimaryHex: "E8F5E9",
            textSecondaryHex: "4CAF50",
            cornerRadius: 16,
            borderWidth: 1,
            glassOpacity: 0.1,
            blurRadius: 20,
            fontDesign: .rounded,
            iconStyle: .sfSymbol,
            animationStyle: .organic,
            radarStyle: .classic,
            radarRingCount: 3,
            radarSweepEnabled: true
        ),
        HUDTheme(
            id: "nordic_frost",
            styleFamily: .nordic,
            name: "Frost",
            subtitle: "Ice Crystal",
            previewImageName: "theme_nordic_frost",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "B3E5FC",
            secondaryHex: "81D4FA",
            accentHex: "4FC3F7",
            backgroundHex: "0A141C",
            alertInfoHex: "81D4FA",
            alertCautionHex: "FFE082",
            alertWarningHex: "FFAB91",
            alertCriticalHex: "EF9A9A",
            textPrimaryHex: "E1F5FE",
            textSecondaryHex: "4FC3F7",
            cornerRadius: 18,
            borderWidth: 1,
            glassOpacity: 0.12,
            blurRadius: 22,
            fontDesign: .rounded,
            iconStyle: .sfSymbol,
            animationStyle: .organic,
            radarStyle: .classic,
            radarRingCount: 3,
            radarSweepEnabled: false
        ),
        HUDTheme(
            id: "nordic_midnight",
            styleFamily: .nordic,
            name: "Midnight Sun",
            subtitle: "Polar Twilight",
            previewImageName: "theme_nordic_midnight",
            isPremium: true,
            trialDurationMinutes: 30,
            primaryHex: "FF8A65",
            secondaryHex: "FFAB91",
            accentHex: "FFE0B2",
            backgroundHex: "1A0A00",
            alertInfoHex: "FFAB91",
            alertCautionHex: "FFE082",
            alertWarningHex: "FF8A65",
            alertCriticalHex: "EF5350",
            textPrimaryHex: "FBE9E7",
            textSecondaryHex: "FF7043",
            cornerRadius: 14,
            borderWidth: 1,
            glassOpacity: 0.11,
            blurRadius: 18,
            fontDesign: .rounded,
            iconStyle: .sfSymbol,
            animationStyle: .organic,
            radarStyle: .classic,
            radarRingCount: 3,
            radarSweepEnabled: true
        ),
    ]
}
